name: Deploy production

on:
  push:
    branches:
      - main
permissions:
  packages: write
  contents: read
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Configurar el soporte para Buildx, que permite construir imágenes de manera optimizada

      - name: Cache Docker layers
        uses: actions/cache@v4  # Habilitar el caching para las capas de Docker y evitar que se reconstruyan siempre

        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2  # Hacer login en GHCR usando las credenciales de GitHub
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Build and push Docker image
        run: |
          # Construir la imagen Docker usando el Dockerfile
          docker build -f Dockerfile -t ghcr.io/${{ github.repository }}:latest .

          # Subir la imagen construida a GHCR
          docker push ghcr.io/${{ github.repository }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: 204.168.214.142
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Conexión exitosa al VPS"

            docker login ghcr.io -u "andrescortesdev" -p ${{ secrets.TOKEN}} 
            docker pull ghcr.io/${{ github.repository }}:latest
            docker stop ${{github.event.repository.name}} || true
            docker rm ${{github.event.repository.name}} || true

            docker run -d --name ${{ github.event.repository.name }} \
                         -p 8080:8080 \
                         ghcr.io/${{ github.repository }}:latest
